// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DAL.Realization.Migrations
{
    [DbContext(typeof(ZooDbContext))]
    partial class ZooDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Realization.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnimalType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FedToTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalType = "Mammal",
                            BirthDate = new DateTime(2020, 4, 18, 19, 43, 19, 883, DateTimeKind.Local).AddTicks(3262),
                            FedToTime = new DateTime(2020, 4, 19, 21, 43, 19, 886, DateTimeKind.Local).AddTicks(2490),
                            FoodType = "Meat",
                            Name = "Alex",
                            Weight = 8000
                        },
                        new
                        {
                            Id = 2,
                            AnimalType = "Bird",
                            BirthDate = new DateTime(2020, 4, 16, 19, 43, 19, 886, DateTimeKind.Local).AddTicks(3955),
                            FedToTime = new DateTime(2020, 4, 19, 19, 43, 19, 886, DateTimeKind.Local).AddTicks(3979),
                            FoodType = "Corn",
                            Name = "Red",
                            Weight = 84
                        },
                        new
                        {
                            Id = 3,
                            AnimalType = "Fish",
                            BirthDate = new DateTime(2020, 4, 16, 19, 43, 19, 886, DateTimeKind.Local).AddTicks(4022),
                            FedToTime = new DateTime(2020, 4, 19, 18, 43, 19, 886, DateTimeKind.Local).AddTicks(4025),
                            FoodType = "Fish feed",
                            Name = "Nemo",
                            Weight = 42
                        });
                });

            modelBuilder.Entity("DAL.Realization.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssimilationMultiplierCoefficient")
                        .HasColumnType("int");

                    b.Property<int>("Calorific")
                        .HasColumnType("int");

                    b.Property<string>("FoodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Food");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssimilationMultiplierCoefficient = 6,
                            Calorific = 30000,
                            FoodType = "Meat",
                            Name = "15 kg of meat",
                            Quantity = 500
                        },
                        new
                        {
                            Id = 2,
                            AssimilationMultiplierCoefficient = 2,
                            Calorific = 2000,
                            FoodType = "Corn",
                            Name = "1 kg of corn",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            AssimilationMultiplierCoefficient = 3,
                            Calorific = 1000,
                            FoodType = "Fish feed",
                            Name = "1 kg of fish corn",
                            Quantity = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
